node {
    stage('prep') {
      println 'prep' 
      println $isBoolean
    }

    stage('build') {
      println 'build'
      println ${params.isBoolean}
    }

    stage('test') {
      println 'test'
    }

    stage('deploy') {
      println 'deploy'
    }
}