node {
    stage('prep') {
      println 'prep' 
    }

    stage('build') {
      println 'build'
      println "${params.isBoolean}"
      echo "flag: ${params.isBoolean}"

    }

    stage('test') {
      println 'test'
    }

    stage('deploy') {
      println 'deploy'
    }
}