node {
    def name = "1111"
    parameters {
        booleanParam(defaultValue: true, description: '', name: 'userFlag')
    }

    stage('prep') {
        println 'prep 1' 
        println 'prep 2' 
    }

    stage('build') {
      println 'build'

      // Prameter
      println "println: ${params.isBoolean}"
      echo "echo: ${params.isBoolean}"
      println "name: ${name}"
      name = "cetauri"

    }

    stage('test') {
      println 'test'
    }

    stage('deploy') {
      println 'deploy'
      println "name: ${name}"
      println "userFlag: ${params.userFlag}"
    }
}
